apiVersion: v1
kind: ConfigMap
metadata:
  name: cities-web-config
  namespace: default
data:
  spring_profiles_active: k8s,seeded
  java_opts: -XX:+UseG1GC -Xmx1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cities-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cities-web
  template:
    metadata:
      name: cities-web
      labels:
        app: cities-web
    spec:
      containers:
      - name: cities-web
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: cities-web-config
                key: spring_profiles_active
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: cities-web-config
                key: java_opts
        #image: us.gcr.io/{project_id}/cities-web:latest
        #image: {prefix}.azurecr.io/{subscription_id}/cities-web:latest
        image: us.gcr.io/fe-cphillipson/cities-web:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /home/app/.cache
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}