version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    #image: us.gcr.io/{project_id}/cities-web:latest
    image: pivotalio/cities-web:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - webapp.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge